### ISSUE TITLE
Release of v1.0.0

### ISSUE THREAD

**Issue by srikon** [rebus-org/Rebus.AmazonS3#4]
The last beta release is 6 months old. How soon will the release v1.0.0 be? We have plans to use it in our application and wondering if there will be a stable release available soon enough.

**Comment by micdah** [comment]
@mookid8000 What do you think, are we ready for a production release?

**Comment by mookid8000** [comment]
Yes 🎉

**Comment by mookid8000** [comment]
I've pushed it to NuGet.org now 😄 thanks for reminding me @srikon and @micdah

**Comment by srikon** [comment]
Thank you @mookid8000 and @micdah for the quick turnaround
