### ISSUE TITLE
reduce number of requests made to S3

### ISSUE THREAD

**Issue by dbierbaum** [rebus-org/Rebus.AmazonS3#5]
Hello, we just started using S3 to store message data to reduce the message size we send to SQS and it was working great, until we saw our bill for S3! Looking at the source code I noticed that in order to Read a message attachment, Rebus makes a HEAD, COPY, and GET request to S3. Combined with the initial PUT to save the attachment that is 4 requests to S3 for every message. We're sending millions of messages a day so every request adds up. 

Would it be possible to add a config option to ignore/not use the 'last read time' (and any other meta data) so we can reduce this to only a PUT and a GET (2 requests to S3 per message)? I'm not sure if Rebus needs this data for anything, but our application certainly doesn't.

**Comment by mookid8000** [comment]
It's now possible to skip updating the "last read time" metadata, whenever an attachment is read.

It's configured by passing `AmazonS3DataBusOptions` options to the configuration extension, e.g. like this:
```csharp
Configure.With(...)
    .(...)
    .Options(o =>
    {
        var options = new AmazonS3DataBusOptions("my-bucket")
        {
            DoNotUpdateLastReadTime = true
        };

        var credentials = new BasicAWSCredentials("access-key", "secret-key");
        var config = new AmazonS3Config();

        o.EnableDataBus().StoreInAmazonS3(credentials, config, options);
    })
    .Start();
```

It's available in Rebus.AmazonS3 1.1.0, which is on NuGet.org now.

Thanks for suggesting this 👍 and thanks for your patience 😉
