### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by flaminscotsman** [rebus-org/Rebus.AmazonS3#6]
Looks like you've done the initial work for Rebus 6 compatability, but there's no nuget package for it.

Do you have a timeline for releasing the changes?

**Comment by mookid8000** [comment]
Damn, sorry! I must have forgotten to push that button! 🙄

I've released it now, so it'll be available on NuGet.org in a few minutes.

PS: Sorry about the slow reply – I've just returned from vacation, so I have had my attention elsewhere for a couple of weeks 😎
